version: "3.8"
services:
  mongo:
    image: mongo
    container_name: mongodb-integration-tests
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: "admin"
      MONGO_INITDB_ROOT_PASSWORD: "root"
    volumes:
      - data:/data
    ports:
      - 27017:27017

volumes:
  data: {}
